apiVersion: v1
kind: List
items:
- apiVersion: core.federation.k8s.io/v1alpha1
  kind: FederatedSecretOverride
  metadata:
    name: test-secret
    namespace: test-namespace
  spec:
    overrides:
    - clusterName: cluster2
      data:
        A: null
